<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Tem certeza que deseja remover esse item?',
    'Attaches' => 'Anexos',
    'Categories' => 'Categorias',
    'Content Ratings' => 'Avaliçaões de Conteúdos',
    'Contents' => 'Conteúdos',
    'Courses' => 'Cursos',
    'Create Attaches' => 'Criar Anexo',
    'Create Categories' => 'Criar Categoria',
    'Create Content Rating' => 'Criar Avaliação de Conteúdo',
    'Create Contents' => 'Criar Conteúdo',
    'Create Courses' => 'Criar Curso',
    'Create Suggestions' => 'Criar Sugestão',
    'Create Users' => 'Criar Usuário',
    'Delete' => 'Remover',
    'Reset' => 'Limpar',
    'Save' => 'Salvar',
    'Search' => 'Pesquisar',
    'Suggestions' => 'Sugestões',
    'The requested page does not exist.' => 'A página buscada não existe',
    'Update' => 'Atualizar',
    'Username' => 'Usuário',
    'Password' => 'Senha',
    'Remember Me' => 'Lembrar de mim',
    'Update Attaches: mode' => '',
    'Update Categories: mode' => '',
    'Update Content Rating: mode' => '',
    'Update Contents: mode' => '',
    'Update Courses: mode' => '',
    'Update Suggestions: mode' => '',
    'Update Users: mode' => '',
    'Users' => 'Usuários',
];
